name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Generate build number file
        run: |
          echo "<p>Build Number: ${{ github.run_number }}</p>" > ./build/build-number.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deploy_url: ${{ steps.set-url.outputs.deploy_url }}

      - name: Set deploy URL
        id: set-url
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "deploy_url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_OUTPUT
          else
            branch_name=$(echo "${{ github.ref }}" | sed -e "s/refs\/heads\///g")
            echo "deploy_url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/$branch_name/" >> $GITHUB_OUTPUT
          fi